#! /usr/local/bin/python

import sys
import codecs
from WebElements.Parser import WebElementTree

def parseFile(fileName, saveChanges=True):
    fileObj = open(fileName, 'r')
    text = fileObj.read().decode('utf8')
    tree = WebElementTree(text)
    fileObj.close()

    if saveChanges:
        text = tree.toHtml(formatted=True)
        fileObj = codecs.open(fileName, encoding='utf-8', mode='w')
        fileObj.write(text)
        fileObj.close()

    return tree

def printDoc():
    print "CleanHTML 0.2 is a forgiving html parser fixer and indenter."
    print "usage: cleanHTML (filename) [write|safe]"
    print ""
    print "safe mode will output warnings without writing the changes to the file."

def main(argv):
    if len(argv) < 2:
        printDoc()
    elif len(argv) < 3:
        parseFile(argv[1])
    elif len(argv) == 3:
        if(argv[2] == "write"):
            parseFile(argv[1])
        else:
            parseFile(argv[1], False)
    else:
        printDoc()

if __name__ == '__main__':
    main(sys.argv)
